name: Build TurboPi OS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: |
          echo "TurboPi OS Build Started!"
